name: deprecated-backend-tests

# This workflow is intentionally deprecated in favor of CI (ci.yml).
# Keeping a no-op placeholder to avoid duplicate runs while preserving history.
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deprecated workflow. Use CI (ci.yml)."
